version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  initdb:
    desc: Run PostgreSQL container with env vars
    cmds:
      - docker run --name postgres \
          -e POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}} \
          -e POSTGRES_USER={{.POSTGRES_USER}} \
          -p {{.POSTGRES_PORT}}:5432 \
          -d postgres:13.21-alpine3.21

  createdb:
    desc: Create a new PostgreSQL database inside the running container
    cmds:
      - docker exec -it postgres createdb --username={{.POSTGRES_USER}} --owner={{.POSTGRES_USER}} {{.POSTGRES_DB}}

  dropdb:
    desc: Drop the PostgreSQL database if it exists
    cmds:
      - docker exec -it postgres dropdb --username={{.POSTGRES_USER}} --if-exists {{.POSTGRES_DB}}

  resetdb:
    desc: Reset the PostgreSQL database by dropping and recreating it
    cmds:
      - task dropdb
      - task createdb

  server:user:
    cmds:
      - go run services/user-service/server.go

  user:gqlgen:
    cmds:
      - gqlgen services/user-service/ generate

  pqsl:user:
    cmds:
      - docker exec -it user-db psql -U root -d user
  
  pqsl:team:
    cmds:
      - docker exec -it team-db psql -U root -d team
  
  pqsl:asset:
    cmds:
      - docker exec -it asset-db psql -U root -d asset

  proto:user:
    cmds:
      - protoc --proto_path=services/user-service/proto --go_out=services/user-service/pb --go_opt=paths=source_relative --go-grpc_out=services/user-service/pb --go-grpc_opt=paths=source_relative services/user-service/proto/user.proto
  proto:team:
    cmds:
      - |
        protoc \
          --proto_path=services/team-service/proto \
          --go_out=services/team-service/pb \
          --go_opt=paths=source_relative \
          --go-grpc_out=services/team-service/pb \
          --go-grpc_opt=paths=source_relative \
          services/team-service/proto/user/user.proto
      - |
        protoc \
          --proto_path=services/team-service/proto \
          --go_out=services/team-service/pb \
          --go_opt=paths=source_relative \
          --go-grpc_out=services/team-service/pb \
          --go-grpc_opt=paths=source_relative \
          services/team-service/proto/team/team.proto

  proto:asset:
    cmds:
      - protoc --proto_path=services/asset-service/proto --go_out=services/asset-service/pb --go_opt=paths=source_relative --go-grpc_out=services/asset-service/pb --go-grpc_opt=paths=source_relative services/asset-service/proto/user.proto

