syntax = "proto3";

package user;

option go_package = "github.com/Thanhbinh1905/go-training-system/services/user-service/pb/user";

enum Role {
  ROLE_UNSPECIFIED = 0;
  MANAGER = 1;
  MEMBER = 2;
}

message BaseResponse {
  bool success = 1;
  string message = 2;
}

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc IsUserExist(GetUserRequest) returns (IsUserExistResponse);
  rpc VerifyAccessToken(VerifyTokenRequest) returns (VerifyTokenResponse);

  rpc GetUsersByIds(GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
}

message GetUserRequest {
  string user_id = 1;
}

message User {
  string user_id = 1;
  string username = 2;
  string email = 3;
  Role role = 4;
  string created_at = 5;
}

message GetUserResponse {
  BaseResponse base = 1;
  User user = 2;
}

message IsUserExistResponse {
  BaseResponse base = 1;
  bool is_exist = 2;
}

message VerifyTokenRequest {
  string access_token = 1;
}

message UserInfo {
  string user_id = 1;
  Role role = 2;
}

message VerifyTokenResponse {
  UserInfo user_info = 1;
  BaseResponse base = 2;
  bool is_valid = 3;
}

message GetUsersByIdsRequest {
  repeated string user_ids = 1;
}

message GetUsersByIdsResponse {
  BaseResponse base = 1;
  repeated GetUserResponse users = 2;
}
