// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: team/team.proto

package team

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_team_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_team_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_team_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{2}
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Team          *Team                  `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_team_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type IsTeamExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	IsExist       bool                   `protobuf:"varint,2,opt,name=is_exist,json=isExist,proto3" json:"is_exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTeamExistResponse) Reset() {
	*x = IsTeamExistResponse{}
	mi := &file_team_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTeamExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTeamExistResponse) ProtoMessage() {}

func (x *IsTeamExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTeamExistResponse.ProtoReflect.Descriptor instead.
func (*IsTeamExistResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{4}
}

func (x *IsTeamExistResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *IsTeamExistResponse) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type GetUserIDsByTeamIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDsByTeamIDRequest) Reset() {
	*x = GetUserIDsByTeamIDRequest{}
	mi := &file_team_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDsByTeamIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDsByTeamIDRequest) ProtoMessage() {}

func (x *GetUserIDsByTeamIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDsByTeamIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDsByTeamIDRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserIDsByTeamIDRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetUserIDsByTeamIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ManagerIds    []string               `protobuf:"bytes,2,rep,name=manager_ids,json=managerIds,proto3" json:"manager_ids,omitempty"` // Danh sách user_id của manager
	MemberIds     []string               `protobuf:"bytes,3,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`    // Danh sách user_id của member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDsByTeamIDResponse) Reset() {
	*x = GetUserIDsByTeamIDResponse{}
	mi := &file_team_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDsByTeamIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDsByTeamIDResponse) ProtoMessage() {}

func (x *GetUserIDsByTeamIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDsByTeamIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDsByTeamIDResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserIDsByTeamIDResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserIDsByTeamIDResponse) GetManagerIds() []string {
	if x != nil {
		return x.ManagerIds
	}
	return nil
}

func (x *GetUserIDsByTeamIDResponse) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type GetManagersByTeamIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ManagerIds    []string               `protobuf:"bytes,2,rep,name=manager_ids,json=managerIds,proto3" json:"manager_ids,omitempty"` // Danh sách user_id của manager
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagersByTeamIDResponse) Reset() {
	*x = GetManagersByTeamIDResponse{}
	mi := &file_team_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagersByTeamIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagersByTeamIDResponse) ProtoMessage() {}

func (x *GetManagersByTeamIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagersByTeamIDResponse.ProtoReflect.Descriptor instead.
func (*GetManagersByTeamIDResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{7}
}

func (x *GetManagersByTeamIDResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetManagersByTeamIDResponse) GetManagerIds() []string {
	if x != nil {
		return x.ManagerIds
	}
	return nil
}

type GetMembersByTeamIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // Danh sách user_id của member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersByTeamIDResponse) Reset() {
	*x = GetMembersByTeamIDResponse{}
	mi := &file_team_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersByTeamIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersByTeamIDResponse) ProtoMessage() {}

func (x *GetMembersByTeamIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersByTeamIDResponse.ProtoReflect.Descriptor instead.
func (*GetMembersByTeamIDResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{8}
}

func (x *GetMembersByTeamIDResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetMembersByTeamIDResponse) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type IsUserTeamManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TeamID        string                 `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTeamManagerRequest) Reset() {
	*x = IsUserTeamManagerRequest{}
	mi := &file_team_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTeamManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTeamManagerRequest) ProtoMessage() {}

func (x *IsUserTeamManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTeamManagerRequest.ProtoReflect.Descriptor instead.
func (*IsUserTeamManagerRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{9}
}

func (x *IsUserTeamManagerRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *IsUserTeamManagerRequest) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type IsUserTeamManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	IsManager     bool                   `protobuf:"varint,2,opt,name=isManager,proto3" json:"isManager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTeamManagerResponse) Reset() {
	*x = IsUserTeamManagerResponse{}
	mi := &file_team_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTeamManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTeamManagerResponse) ProtoMessage() {}

func (x *IsUserTeamManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTeamManagerResponse.ProtoReflect.Descriptor instead.
func (*IsUserTeamManagerResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{10}
}

func (x *IsUserTeamManagerResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *IsUserTeamManagerResponse) GetIsManager() bool {
	if x != nil {
		return x.IsManager
	}
	return false
}

var File_team_team_proto protoreflect.FileDescriptor

const file_team_team_proto_rawDesc = "" +
	"\n" +
	"\x0fteam/team.proto\x12\x04team\"B\n" +
	"\fBaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"R\n" +
	"\x04Team\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"Y\n" +
	"\x0fGetTeamResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x1e\n" +
	"\x04team\x18\x02 \x01(\v2\n" +
	".team.TeamR\x04team\"X\n" +
	"\x13IsTeamExistResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x19\n" +
	"\bis_exist\x18\x02 \x01(\bR\aisExist\"4\n" +
	"\x19GetUserIDsByTeamIDRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x84\x01\n" +
	"\x1aGetUserIDsByTeamIDResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x1f\n" +
	"\vmanager_ids\x18\x02 \x03(\tR\n" +
	"managerIds\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\tR\tmemberIds\"f\n" +
	"\x1bGetManagersByTeamIDResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x1f\n" +
	"\vmanager_ids\x18\x02 \x03(\tR\n" +
	"managerIds\"c\n" +
	"\x1aGetMembersByTeamIDResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\tR\tmemberIds\"J\n" +
	"\x18IsUserTeamManagerRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06teamID\x18\x02 \x01(\tR\x06teamID\"a\n" +
	"\x19IsUserTeamManagerResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.team.BaseResponseR\x04base\x12\x1c\n" +
	"\tisManager\x18\x02 \x01(\bR\tisManager2\xe8\x03\n" +
	"\vTeamService\x126\n" +
	"\aGetTeam\x12\x14.team.GetTeamRequest\x1a\x15.team.GetTeamResponse\x12>\n" +
	"\vIsTeamExist\x12\x14.team.GetTeamRequest\x1a\x19.team.IsTeamExistResponse\x12W\n" +
	"\x12GetUserIDsByTeamID\x12\x1f.team.GetUserIDsByTeamIDRequest\x1a .team.GetUserIDsByTeamIDResponse\x12Y\n" +
	"\x13GetManagersByTeamID\x12\x1f.team.GetUserIDsByTeamIDRequest\x1a!.team.GetManagersByTeamIDResponse\x12W\n" +
	"\x12GetMembersByTeamID\x12\x1f.team.GetUserIDsByTeamIDRequest\x1a .team.GetMembersByTeamIDResponse\x12T\n" +
	"\x11IsUserTeamManager\x12\x1e.team.IsUserTeamManagerRequest\x1a\x1f.team.IsUserTeamManagerResponseBKZIgithub.com/Thanhbinh1905/go-training-system/services/team-service/pb/teamb\x06proto3"

var (
	file_team_team_proto_rawDescOnce sync.Once
	file_team_team_proto_rawDescData []byte
)

func file_team_team_proto_rawDescGZIP() []byte {
	file_team_team_proto_rawDescOnce.Do(func() {
		file_team_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_team_proto_rawDesc), len(file_team_team_proto_rawDesc)))
	})
	return file_team_team_proto_rawDescData
}

var file_team_team_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_team_team_proto_goTypes = []any{
	(*BaseResponse)(nil),                // 0: team.BaseResponse
	(*GetTeamRequest)(nil),              // 1: team.GetTeamRequest
	(*Team)(nil),                        // 2: team.Team
	(*GetTeamResponse)(nil),             // 3: team.GetTeamResponse
	(*IsTeamExistResponse)(nil),         // 4: team.IsTeamExistResponse
	(*GetUserIDsByTeamIDRequest)(nil),   // 5: team.GetUserIDsByTeamIDRequest
	(*GetUserIDsByTeamIDResponse)(nil),  // 6: team.GetUserIDsByTeamIDResponse
	(*GetManagersByTeamIDResponse)(nil), // 7: team.GetManagersByTeamIDResponse
	(*GetMembersByTeamIDResponse)(nil),  // 8: team.GetMembersByTeamIDResponse
	(*IsUserTeamManagerRequest)(nil),    // 9: team.IsUserTeamManagerRequest
	(*IsUserTeamManagerResponse)(nil),   // 10: team.IsUserTeamManagerResponse
}
var file_team_team_proto_depIdxs = []int32{
	0,  // 0: team.GetTeamResponse.base:type_name -> team.BaseResponse
	2,  // 1: team.GetTeamResponse.team:type_name -> team.Team
	0,  // 2: team.IsTeamExistResponse.base:type_name -> team.BaseResponse
	0,  // 3: team.GetUserIDsByTeamIDResponse.base:type_name -> team.BaseResponse
	0,  // 4: team.GetManagersByTeamIDResponse.base:type_name -> team.BaseResponse
	0,  // 5: team.GetMembersByTeamIDResponse.base:type_name -> team.BaseResponse
	0,  // 6: team.IsUserTeamManagerResponse.base:type_name -> team.BaseResponse
	1,  // 7: team.TeamService.GetTeam:input_type -> team.GetTeamRequest
	1,  // 8: team.TeamService.IsTeamExist:input_type -> team.GetTeamRequest
	5,  // 9: team.TeamService.GetUserIDsByTeamID:input_type -> team.GetUserIDsByTeamIDRequest
	5,  // 10: team.TeamService.GetManagersByTeamID:input_type -> team.GetUserIDsByTeamIDRequest
	5,  // 11: team.TeamService.GetMembersByTeamID:input_type -> team.GetUserIDsByTeamIDRequest
	9,  // 12: team.TeamService.IsUserTeamManager:input_type -> team.IsUserTeamManagerRequest
	3,  // 13: team.TeamService.GetTeam:output_type -> team.GetTeamResponse
	4,  // 14: team.TeamService.IsTeamExist:output_type -> team.IsTeamExistResponse
	6,  // 15: team.TeamService.GetUserIDsByTeamID:output_type -> team.GetUserIDsByTeamIDResponse
	7,  // 16: team.TeamService.GetManagersByTeamID:output_type -> team.GetManagersByTeamIDResponse
	8,  // 17: team.TeamService.GetMembersByTeamID:output_type -> team.GetMembersByTeamIDResponse
	10, // 18: team.TeamService.IsUserTeamManager:output_type -> team.IsUserTeamManagerResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_team_team_proto_init() }
func file_team_team_proto_init() {
	if File_team_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_team_proto_rawDesc), len(file_team_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_team_proto_goTypes,
		DependencyIndexes: file_team_team_proto_depIdxs,
		MessageInfos:      file_team_team_proto_msgTypes,
	}.Build()
	File_team_team_proto = out.File
	file_team_team_proto_goTypes = nil
	file_team_team_proto_depIdxs = nil
}
