// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: team/team.proto

package team

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamService_GetTeam_FullMethodName             = "/team.TeamService/GetTeam"
	TeamService_IsTeamExist_FullMethodName         = "/team.TeamService/IsTeamExist"
	TeamService_GetUserIDsByTeamID_FullMethodName  = "/team.TeamService/GetUserIDsByTeamID"
	TeamService_GetManagersByTeamID_FullMethodName = "/team.TeamService/GetManagersByTeamID"
	TeamService_GetMembersByTeamID_FullMethodName  = "/team.TeamService/GetMembersByTeamID"
	TeamService_IsUserTeamManager_FullMethodName   = "/team.TeamService/IsUserTeamManager"
)

// TeamServiceClient is the client API for TeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamServiceClient interface {
	GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error)
	IsTeamExist(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*IsTeamExistResponse, error)
	// Lấy danh sách user_id thuộc về 1 team (gồm cả member & manager)
	GetUserIDsByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetUserIDsByTeamIDResponse, error)
	// (Tuỳ chọn) Tách riêng member/manager nếu cần
	GetManagersByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetManagersByTeamIDResponse, error)
	GetMembersByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetMembersByTeamIDResponse, error)
	IsUserTeamManager(ctx context.Context, in *IsUserTeamManagerRequest, opts ...grpc.CallOption) (*IsUserTeamManagerResponse, error)
}

type teamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamServiceClient(cc grpc.ClientConnInterface) TeamServiceClient {
	return &teamServiceClient{cc}
}

func (c *teamServiceClient) GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamResponse)
	err := c.cc.Invoke(ctx, TeamService_GetTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) IsTeamExist(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*IsTeamExistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsTeamExistResponse)
	err := c.cc.Invoke(ctx, TeamService_IsTeamExist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetUserIDsByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetUserIDsByTeamIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserIDsByTeamIDResponse)
	err := c.cc.Invoke(ctx, TeamService_GetUserIDsByTeamID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetManagersByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetManagersByTeamIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagersByTeamIDResponse)
	err := c.cc.Invoke(ctx, TeamService_GetManagersByTeamID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetMembersByTeamID(ctx context.Context, in *GetUserIDsByTeamIDRequest, opts ...grpc.CallOption) (*GetMembersByTeamIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembersByTeamIDResponse)
	err := c.cc.Invoke(ctx, TeamService_GetMembersByTeamID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) IsUserTeamManager(ctx context.Context, in *IsUserTeamManagerRequest, opts ...grpc.CallOption) (*IsUserTeamManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsUserTeamManagerResponse)
	err := c.cc.Invoke(ctx, TeamService_IsUserTeamManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamServiceServer is the server API for TeamService service.
// All implementations must embed UnimplementedTeamServiceServer
// for forward compatibility.
type TeamServiceServer interface {
	GetTeam(context.Context, *GetTeamRequest) (*GetTeamResponse, error)
	IsTeamExist(context.Context, *GetTeamRequest) (*IsTeamExistResponse, error)
	// Lấy danh sách user_id thuộc về 1 team (gồm cả member & manager)
	GetUserIDsByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetUserIDsByTeamIDResponse, error)
	// (Tuỳ chọn) Tách riêng member/manager nếu cần
	GetManagersByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetManagersByTeamIDResponse, error)
	GetMembersByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetMembersByTeamIDResponse, error)
	IsUserTeamManager(context.Context, *IsUserTeamManagerRequest) (*IsUserTeamManagerResponse, error)
	mustEmbedUnimplementedTeamServiceServer()
}

// UnimplementedTeamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamServiceServer struct{}

func (UnimplementedTeamServiceServer) GetTeam(context.Context, *GetTeamRequest) (*GetTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeam not implemented")
}
func (UnimplementedTeamServiceServer) IsTeamExist(context.Context, *GetTeamRequest) (*IsTeamExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsTeamExist not implemented")
}
func (UnimplementedTeamServiceServer) GetUserIDsByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetUserIDsByTeamIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIDsByTeamID not implemented")
}
func (UnimplementedTeamServiceServer) GetManagersByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetManagersByTeamIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagersByTeamID not implemented")
}
func (UnimplementedTeamServiceServer) GetMembersByTeamID(context.Context, *GetUserIDsByTeamIDRequest) (*GetMembersByTeamIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembersByTeamID not implemented")
}
func (UnimplementedTeamServiceServer) IsUserTeamManager(context.Context, *IsUserTeamManagerRequest) (*IsUserTeamManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserTeamManager not implemented")
}
func (UnimplementedTeamServiceServer) mustEmbedUnimplementedTeamServiceServer() {}
func (UnimplementedTeamServiceServer) testEmbeddedByValue()                     {}

// UnsafeTeamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamServiceServer will
// result in compilation errors.
type UnsafeTeamServiceServer interface {
	mustEmbedUnimplementedTeamServiceServer()
}

func RegisterTeamServiceServer(s grpc.ServiceRegistrar, srv TeamServiceServer) {
	// If the following call pancis, it indicates UnimplementedTeamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamService_ServiceDesc, srv)
}

func _TeamService_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_GetTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeam(ctx, req.(*GetTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_IsTeamExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).IsTeamExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_IsTeamExist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).IsTeamExist(ctx, req.(*GetTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetUserIDsByTeamID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDsByTeamIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetUserIDsByTeamID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_GetUserIDsByTeamID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetUserIDsByTeamID(ctx, req.(*GetUserIDsByTeamIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetManagersByTeamID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDsByTeamIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetManagersByTeamID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_GetManagersByTeamID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetManagersByTeamID(ctx, req.(*GetUserIDsByTeamIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetMembersByTeamID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDsByTeamIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetMembersByTeamID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_GetMembersByTeamID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetMembersByTeamID(ctx, req.(*GetUserIDsByTeamIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_IsUserTeamManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserTeamManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).IsUserTeamManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamService_IsUserTeamManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).IsUserTeamManager(ctx, req.(*IsUserTeamManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamService_ServiceDesc is the grpc.ServiceDesc for TeamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "team.TeamService",
	HandlerType: (*TeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeam",
			Handler:    _TeamService_GetTeam_Handler,
		},
		{
			MethodName: "IsTeamExist",
			Handler:    _TeamService_IsTeamExist_Handler,
		},
		{
			MethodName: "GetUserIDsByTeamID",
			Handler:    _TeamService_GetUserIDsByTeamID_Handler,
		},
		{
			MethodName: "GetManagersByTeamID",
			Handler:    _TeamService_GetManagersByTeamID_Handler,
		},
		{
			MethodName: "GetMembersByTeamID",
			Handler:    _TeamService_GetMembersByTeamID_Handler,
		},
		{
			MethodName: "IsUserTeamManager",
			Handler:    _TeamService_IsUserTeamManager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "team/team.proto",
}
